# Generated by Django 3.1 on 2020-10-23 02:55

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelar', models.CharField(blank=True, default='S.Pd.', max_length=7, null=True)),
                ('pas_photo', models.ImageField(blank=True, null=True, upload_to='photo-guru')),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('alamat', models.CharField(blank=True, max_length=30, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('status_guru', models.CharField(blank=True, choices=[('lepas', 'Lepas'), ('tetap', 'Tetap')], default='tetap', max_length=10, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tahun_ajaran', models.CharField(choices=[('2015', '2015/2016'), ('2016', '2016/2017'), ('2017', '2017/2018'), ('2018', '2018/2019'), ('2019', '2019/2020'), ('2020', '2020/2021'), ('2021', '2021/2022'), ('2022', '2022/2023'), ('2023', '2023/2024'), ('2024', '2024/2025'), ('2025', '2025/2026'), ('2026', '2026/2027'), ('2027', '2027/2028'), ('2028', '2028/2029'), ('2029', '2029/2030'), ('2030', '2030/2031')], default='2020', max_length=4)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, choices=[('semester 1', 'Semester 1'), ('semester 2', 'Semester 2')], default='semester 1', max_length=10, null=True)),
                ('guru_pengampu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.guru')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.kelas')),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('sejarah', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'sekolah',
            },
        ),
        migrations.CreateModel(
            name='WaliKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(choices=[('2015', '2015/2016'), ('2016', '2016/2017'), ('2017', '2017/2018'), ('2018', '2018/2019'), ('2019', '2019/2020'), ('2020', '2020/2021'), ('2021', '2021/2022'), ('2022', '2022/2023'), ('2023', '2023/2024'), ('2024', '2024/2025'), ('2025', '2025/2026'), ('2026', '2026/2027'), ('2027', '2027/2028'), ('2028', '2028/2029'), ('2029', '2029/2030'), ('2030', '2030/2031')], default='2020', max_length=4)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
            ],
            options={
                'verbose_name_plural': 'Wali Kelas',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis_siswa', models.CharField(default='', max_length=15, unique=True)),
                ('nisn_siswa', models.CharField(default='', max_length=15, unique=True)),
                ('pas_photo', models.ImageField(blank=True, null=True, upload_to='photo-siswa')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('nama_orang_tua', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pekerjaan_orang_tua', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=30, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('asal_sekolah', models.CharField(blank=True, max_length=100, null=True)),
                ('status_siswa', models.CharField(blank=True, choices=[('calon', 'Calon'), ('tetap', 'Tetap'), ('pindahan', 'Pindahan')], default='tetap', max_length=10, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_cover', models.ImageField(blank=True, null=True, upload_to='photo-prestasi')),
                ('deskripsi', models.TextField(blank=True, max_length=500, null=True)),
                ('tanggal_kegiatan', models.DateField(blank=True, null=True)),
                ('ranking_prestasi', models.CharField(blank=True, choices=[('a', 'Juara Umum'), ('b', 'Juara I'), ('c', 'Juara II'), ('d', 'Juara III'), ('e', 'Juara Harapan'), ('f', 'Juara Harapan I'), ('g', 'Juara Harapan II'), ('h', 'Juara Harapan III')], default='juara-umum', max_length=20, null=True)),
                ('tingkat_prestasi', models.CharField(blank=True, choices=[('a', 'Sekolah'), ('b', 'Desa'), ('c', 'Kecamatan'), ('d', 'Kabupaten'), ('e', 'Provinsi'), ('f', 'Nasional'), ('g', 'Internasional')], default='sekolah', max_length=15, null=True)),
                ('tahun_ajaran', models.CharField(blank=True, choices=[('2015', '2015/2016'), ('2016', '2016/2017'), ('2017', '2017/2018'), ('2018', '2018/2019'), ('2019', '2019/2020'), ('2020', '2020/2021'), ('2021', '2021/2022'), ('2022', '2022/2023'), ('2023', '2023/2024'), ('2024', '2024/2025'), ('2025', '2025/2026'), ('2026', '2026/2027'), ('2027', '2027/2028'), ('2028', '2028/2029'), ('2029', '2029/2030'), ('2030', '2030/2031')], default='2020', max_length=4, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pemegang_prestasi_guru', models.ManyToManyField(blank=True, to='sekolah.Guru')),
                ('pemegang_prestasi_siswa', models.ManyToManyField(blank=True, to='sekolah.Siswa')),
            ],
            options={
                'verbose_name_plural': 'Prestasi Sekolah',
            },
        ),
        migrations.CreateModel(
            name='NilaiMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_angka_1', models.IntegerField(blank=True, default=0, null=True)),
                ('nilai_angka_2', models.IntegerField(blank=True, default=0, null=True)),
                ('nilai_huruf_1', models.CharField(blank=True, choices=[('a', 'Sangat Baik'), ('b', 'Baik'), ('c', 'Cukup'), ('d', 'Kurang')], default='d', max_length=15, null=True)),
                ('nilai_huruf_2', models.CharField(blank=True, choices=[('a', 'Sangat Baik'), ('b', 'Baik'), ('c', 'Cukup'), ('d', 'Kurang')], default='d', max_length=15, null=True)),
                ('deskripsi_1', models.CharField(blank=True, max_length=150, null=True)),
                ('deskripsi_2', models.CharField(blank=True, max_length=150, null=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
            ],
            options={
                'verbose_name_plural': 'Nilai Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='KepalaSekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(choices=[('2015', '2015/2016'), ('2016', '2016/2017'), ('2017', '2017/2018'), ('2018', '2018/2019'), ('2019', '2019/2020'), ('2020', '2020/2021'), ('2021', '2021/2022'), ('2022', '2022/2023'), ('2023', '2023/2024'), ('2024', '2024/2025'), ('2025', '2025/2026'), ('2026', '2026/2027'), ('2027', '2027/2028'), ('2028', '2028/2029'), ('2029', '2029/2030'), ('2030', '2030/2031')], default='2020', max_length=4)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.guru')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'verbose_name_plural': 'Kepala Sekolah',
            },
        ),
        migrations.AddField(
            model_name='kelas',
            name='siswa',
            field=models.ManyToManyField(blank=True, related_name='daftar_siswa', to='sekolah.Siswa'),
        ),
    ]
