# Generated by Django 3.1 on 2020-10-23 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(default='2020', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='kelas',
            name='tahun_ajaran',
            field=models.ForeignKey(default='2020', on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunpelajaran'),
        ),
        migrations.AlterField(
            model_name='kepalasekolah',
            name='tahun_ajaran',
            field=models.ForeignKey(default='2020', on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunpelajaran'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='tahun_ajaran',
            field=models.ForeignKey(default='2020', on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunpelajaran'),
        ),
        migrations.AlterField(
            model_name='walikelas',
            name='tahun_ajaran',
            field=models.ForeignKey(default='2020', on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunpelajaran'),
        ),
    ]
