# Generated by Django 2.2 on 2021-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type_staff',
            field=models.CharField(blank=True, choices=[('staff-admin', 'Staff Admin'), ('staff-keuangan', 'Staff Keuangan')], default='tetap', max_length=15, null=True),
        ),
    ]
