# Generated by Django 3.1 on 2020-10-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_auto_20201023_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walikelas',
            name='tahun_ajaran',
        ),
    ]
