# Generated by Django 3.1 on 2020-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_remove_walikelas_tahun_ajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='status_siswa',
            field=models.CharField(blank=True, choices=[('calon', 'Calon'), ('tetap', 'Tetap'), ('pindahan', 'Pindahan'), ('alumni', 'Alumni')], default='tetap', max_length=10, null=True),
        ),
    ]
